test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

dropbox:
  service: Dropbox
  app_key: <%=Rails.application.credentials.dig(:dropbox, :app_key)%>
  app_secret: <%=Rails.application.credentials.dig(:dropbox, :app_secret)%>
  access_token: <%=Rails.application.credentials.dig(:dropbox, :access_token)%>
  user_id: <%=Rails.application.credentials.dig(:dropbox, :user_id)%>
  access_type: app